#!/bin/sh /etc/rc.common

START=90
STOP=15

SERVICE_DAEMONIZE=1

start()
{
	config_load "udp2raw"	
	config_get enabled config enabled 0

	[ "$enabled" = 0 ] && return 0

	config_get args config args

	service_start /usr/bin/udp2raw $args
}

stop()
{
	service_stop /usr/bin/udp2raw
}
