#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-lighttpd ) && rm -f /etc/uci-defaults/luci-lighttpd
	chmod 755 /etc/init.d/lighttpd >/dev/null 2>&1
	/etc/init.d/lighttpd enable >/dev/null 2>&1
	exit 0
}
