#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-pdnsd ) && rm -f /etc/uci-defaults/luci-pdnsd
	chmod 755 /etc/init.d/pdnsd >/dev/null 2>&1
	/etc/init.d/pdnsd enable >/dev/null 2>&1
	exit 0
}
