#!/bin/sh /etc/rc.common

START=90
STOP=15

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start()
{
	config_load "chinadns"
	config_get enabled config enabled
	config_get dns config dns
	config_get port config port

	[ $enabled = '0' ] && exit 0

	service_start /usr/bin/chinadns \
		-c /etc/chinadns_chnroute.txt \
		-m \
		-p $port \
		-s "$dns"

	uci del dhcp.@dnsmasq[-1].server
	uci set dhcp.@dnsmasq[-1].noresolv=1
	uci add_list dhcp.@dnsmasq[-1].server=127.0.0.1#$port
	uci commit dhcp
	/etc/init.d/dnsmasq restart
}

stop()
{
	service_stop /usr/bin/chinadns
}
