#!/bin/sh /etc/rc.common

START=90
STOP=15
PIDFILE='/tmp/run/chinadns.pid'

start()
{
	config_load "chinadns"
	local enabled dns port
	config_get enabled config enabled
	config_get dns config dns
	config_get port config port

	[ $enabled = '0' ] && exit 0

	if [ -f $PIDFILE ];then
		echo "already started: $PIDFILE exists"
		return 1
	fi

	chinadns \
		-l /etc/chinadns_iplist.txt \
		-c /etc/chinadns_chnroute.txt \
		-d \
		-p $port \
		-s "$dns" &
	echo $! > $PIDFILE

	uci del dhcp.@dnsmasq[-1].server
	uci set dhcp.@dnsmasq[-1].noresolv=1
	uci add_list dhcp.@dnsmasq[-1].server=127.0.0.1#$port
	uci commit dhcp
	/etc/init.d/dnsmasq restart
}

stop()
{
	[ -f $PIDFILE ] && {
		kill -9 `cat $PIDFILE`
		rm $PIDFILE
	}
}
