#!/bin/sh

[ "$ACTION" = "remove" ] || exit 0

PROTO="`ubus call network.interface.$INTERFACE status | grep proto | grep -q openconnect`"

[ $PROTO -eq 0 ] || exit 0

rm -f \
/etc/config/ca-vpn-$INTERFACE.pem \
/etc/config/user-cert-vpn-$INTERFACE.pem \
/etc/config/user-key-vpn-$INTERFACE.pem
