#!/bin/sh
TEMPFILE=/var/etc/tun2socks

[ "$INTERFACE" = wan ] || exit 0

[ -f "$TEMPFILE" ] || exit 0

INTF="$(cat $TEMPFILE)"

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] && ifup $INTF
}

[ "$ACTION" = ifdown ] && {
	ifdown $INTF
	rm -f $TEMPFILE
}
