#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-shadowsocks ) && rm -f /etc/uci-defaults/luci-shadowsocks
	chmod 755 /etc/init.d/shadowsocks >/dev/null 2>&1
	/etc/init.d/shadowsocks enable >/dev/null 2>&1
	exit 0
}
