#!/bin/sh /etc/rc.common

START=95

start() {
	config_load "vsftpd"
	local enabled
	config_get enabled config enabled
	[ $enabled -eq 0 ] && {
		return 0
	}
	mkdir -m 0755 -p /var/run/vsftpd
	service_start /usr/sbin/vsftpd
}

stop() {
	service_stop /usr/sbin/vsftpd
}
