#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-vsftpd ) && rm -f /etc/uci-defaults/luci-vsftpd
	chmod 755 /etc/init.d/vsftpd-ra >/dev/null 2>&1
	/etc/init.d/vsftpd-ra enable >/dev/null 2>&1
	exit 0
}
