#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-aria2 ) && rm -f /etc/uci-defaults/luci-aria2
	chmod 755 /etc/init.d/aria2-ra >/dev/null 2>&1
	/etc/init.d/aria2-ra enable >/dev/null 2>&1
	exit 0
}
