--- a/luci/contrib/package/luci/Makefile
+++ b/luci/contrib/package/luci/Makefile
@@ -455,6 +455,29 @@
 
 $(eval $(call application,watchcat,LuCI Support for Watchcat,\
 	+PACKAGE_luci-app-watchcat:watchcat))
+
+$(eval $(call application,aria2,LuCI Support for aria2,\
+	+PACKAGE_luci-app-aria2:aria2 \
+	+PACKAGE_luci-app-aria2:curl \
+	+PACKAGE_luci-app-aria2:wget \
+	+PACKAGE_luci-app-aria2:openssl-util))
+
+$(eval $(call application,shadowsocks,LuCI Support for shadowsocks,\
+	+PACKAGE_luci-app-shadowsocks:shadowsocks-libev \
+	+PACKAGE_luci-app-shadowsocks:libev \
+	+PACKAGE_luci-app-shadowsocks:kmod-ipt-ipset \
+	+PACKAGE_luci-app-shadowsocks:ipset))
+
+$(eval $(call application,vsftpd,LuCI Support for vsftpd,\
+	+PACKAGE_luci-app-vsftpd:vsftpd-tls))
+
+$(eval $(call application,pdnsd,LuCI Support for pdnsd,\
+	+PACKAGE_luci-app-pdnsd:pdnsd))
+
+$(eval $(call application,redsocks2,LuCI Support for redsocks2,\
+	+PACKAGE_luci-app-redsocks2:redsocks2 \
+	+PACKAGE_luci-app-redsocks2:kmod-ipt-ipset \
+	+PACKAGE_luci-app-redsocks2:ipset))
 
 ### Server Gateway Interfaces ###
 define sgi
