--- a/luci/contrib/package/luci/Makefile
+++ b/luci/contrib/package/luci/Makefile
@@ -456,6 +456,33 @@
 $(eval $(call application,watchcat,LuCI Support for Watchcat,\
 	+PACKAGE_luci-app-watchcat:watchcat))
 
+$(eval $(call application,aria2,LuCI Support for aria2,\
+	+PACKAGE_luci-app-aria2:aria2 \
+	+PACKAGE_luci-app-aria2:curl \
+	+PACKAGE_luci-app-aria2:wget \
+	+PACKAGE_luci-app-aria2:openssl-util))
+
+$(eval $(call application,shadowsocks,LuCI Support for shadowsocks,\
+	+PACKAGE_luci-app-shadowsocks:shadowsocks-libev \
+	+PACKAGE_luci-app-shadowsocks:libev \
+	+PACKAGE_luci-app-shadowsocks:kmod-ipt-ipset \
+	+PACKAGE_luci-app-shadowsocks:ipset))
+
+$(eval $(call application,lighttpd,LuCI Support for lighttpd,\
+	+PACKAGE_luci-app-lighttpd:lighttpd \
+	+PACKAGE_luci-app-lighttpd:lighttpd-mod-cgi))
+
+$(eval $(call application,vsftpd,LuCI Support for vsftpd,\
+	+PACKAGE_luci-app-vsftpd:vsftpd-tls))
+
+$(eval $(call application,pdnsd,LuCI Support for pdnsd,\
+	+PACKAGE_luci-app-pdnsd:pdnsd))
+
+$(eval $(call application,redsocks,LuCI Support for redsocks,\
+	+PACKAGE_luci-app-redsocks:redsocks2 \
+	+PACKAGE_luci-app-redsocks:kmod-ipt-ipset \
+	+PACKAGE_luci-app-redsocks:ipset))
+
 ### Server Gateway Interfaces ###
 define sgi
   define Package/luci-sgi-$(1)

